#!/bin/bash

set -e

[ "$1" == "" ] && echo "Usage: $0 <year>" && exit 1
year=$1

. structure.bash
. commonFunctions.bash
cd generated

rm -Rf crls-${year}
mkdir -p crls-${year}
for month in {01..12}; do
    BASE=crls-${year}/$year-$month
    mkdir -p $BASE
    cp root.ca/${year}_${month}.crl $BASE/root.crl
    for ca in "${STRUCT_CAS[@]}"; do
        cp $ca.ca/${year}_${month}.crl $BASE/$ca.crl
    done
done

pushd crls-${year}
rm -f crl-passwords1.txt crl-passwords2.txt
for i in *; do
    PASSW1=`head -c15 /dev/urandom | base64`
    PASSW2=`head -c15 /dev/urandom | base64`
    echo "Crypting CRL $i"
    echo "$i: $PASSW1" >> crl-passwords1.txt
    echo "$i: $PASSW2" >> crl-passwords2.txt
    tar c -C $i . | openssl enc -e -kfile <(echo -n "$PASSW1$PASSW2") -md sha256 -aes-256-cbc > $i.tar.aes-256-cbc
    PASSW1=
    PASSW2=

done
popd
