#!/bin/bash

set -e
[ "$1" == "" ] && echo "Usage: $0 <year>" && exit 1
year=$1

. structure.bash
cd generated

mkdir -p signer-config
for ca in $STRUCT_CAS; do
    for i in $TIME_IDX; do
        mkdir -p signer-config/ca/${ca}_${year}_${i}
        cp ${year}/ca/${ca}_${year}_${i}.crt  signer-config/ca/${ca}_${year}_${i}/ca.crt
    done
done

tar czf signer-client-$year.tar.gz -C .. profiles -C generated/signer-config keys ca

# Updating for server
rm signer-config/keys/signer_*

for ca in $STRUCT_CAS; do
    for i in $TIME_IDX; do
        cp ${year}/ca/${ca}_${year}_${i}.key  signer-config/ca/${ca}_${year}_${i}/ca.key
    done
done

tar czf signer-server-$year.tar.gz -C .. profiles -C generated/signer-config keys ca

rm -R signer-config
