#!/bin/bash
DOMAIN="cacert.org"
KEYSIZE=4096
PRIVATEPW="changeit"

[ -f config ] && . ./config

STRUCT_CAS="env unassured assured codesign orga orgaSign"
SERVER_KEYS="api secure www static signer_server signer_client mail"
TIME_IDX="1 2"
points[1]="0101000000Z"
points[2]="0601000000Z"

ROOT_VALIDITY="-startdate 20150101000000Z -enddate 20300101000000Z"
